#!/bin/bash
echo "Checking Vercel project configuration..."
echo ""
echo "To fix the database issue, you need to:"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your 'AutoPrep-Team' project"
echo "3. Go to 'Storage' tab"
echo "4. Click 'Create Database' → Select 'Postgres'"
echo "5. Follow the prompts to create a Vercel Postgres database"
echo "6. Vercel will automatically add POSTGRES_URL to your environment variables"
echo "7. Redeploy your application"
echo ""
echo "OR if you already have a Postgres database:"
echo ""
echo "1. Go to Settings → Environment Variables"
echo "2. Add POSTGRES_URL with your database connection string"
echo "3. Make sure it uses the POOLED connection (port 6543, not 5432)"
echo "4. Redeploy"
echo ""
echo "The connection string should look like:"
echo "postgres://username:password@host:6543/database?sslmode=require"
