#!/bin/bash

echo "=========================================="
echo "Setting POSTGRES_URL in Vercel"
echo "=========================================="
echo ""
echo "To set the POSTGRES_URL environment variable in Vercel:"
echo ""
echo "1. Go to: https://vercel.com/scottsumerford/autoprep-team/settings/environment-variables"
echo ""
echo "2. Click 'Add New' button"
echo ""
echo "3. Enter the following:"
echo "   Name: POSTGRES_URL"
echo "   Value: postgresql://postgres.kmswrzzlirdfnzzbnrpo:imAVAKBD6QwffO2z@aws-1-us-east-1.pooler.supabase.com:6543/postgres"
echo "   Environments: Select all (Production, Preview, Development)"
echo ""
echo "4. Click 'Save'"
echo ""
echo "5. Redeploy the application:"
echo "   - Go to Deployments tab"
echo "   - Click the three dots (...) on the latest deployment"
echo "   - Click 'Redeploy'"
echo ""
echo "=========================================="
echo "OR use the Vercel CLI (if authenticated):"
echo "=========================================="
echo ""
echo "vercel env add POSTGRES_URL production"
echo "# Then paste the connection string when prompted"
echo ""
echo "vercel env add POSTGRES_URL preview"
echo "# Then paste the connection string when prompted"
echo ""
echo "vercel env add POSTGRES_URL development"
echo "# Then paste the connection string when prompted"
echo ""
echo "Connection string:"
echo "postgresql://postgres.kmswrzzlirdfnzzbnrpo:imAVAKBD6QwffO2z@aws-1-us-east-1.pooler.supabase.com:6543/postgres"
echo ""
